/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yainted.gui;
import yainted.gui.FileChooser;
import yainted.game.GameController;
import yainted.model.Question;
import yainted.game.Player;

/**
 *
 * @author Tyham
 */
public class GameView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameView.class.getName());
    private javax.swing.JPanel currentPanel;
    private GameController controller;
    private GameScreen gameScreen;
    /**
     * Creates new form JeopardyWindow
     * @param control
     */
    public GameView(GameController control) 
    {
        this.controller = control;
        initComponents();
        
        // Set up the layout before adding components
        getContentPane().setLayout(new java.awt.BorderLayout());
        
        currentPanel = new FileChooser(this);
        add(currentPanel, java.awt.BorderLayout.CENTER);
        
        // Pack and center the window
        pack();
        setLocationRelativeTo(null); // Center the window
        setVisible(true);
    }
    public void setGameScreen(GameScreen screen)
    {
        this.gameScreen = screen;
    }
    public GameScreen getGameScreen()
    {
        return this.gameScreen;
    }
    public void sendFile(String path)
    {
        this.controller.getFilePath(path);
    }
    public void sendPlayers(java.util.ArrayList<String> players)
    {
        this.controller.getPlayers(players);
    }
    public java.util.ArrayList<Player> getPlayers()
    {
        return this.controller.sendPlayersToView();
    }
    public Question selectQuestion (String value, String category)
    {
        Question question = this.controller.selectQuestion(value, category);
        return question;
    }
    public Boolean sendAnswer (String ans)
    {
        return controller.validateAnswer(ans);
    }
    public Question getCurrentQuestion()
    {
        return controller.getCurrentQuestion();
    }
    public void sendReportFormat(String format)
    {
        this.controller.setReportFormat(format);
    }
    public void switchPanel(javax.swing.JPanel newPanel)
    {
        remove(currentPanel);
                
        currentPanel = newPanel;
        add(currentPanel, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
        pack();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
