/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yainted.gui;


/**
 *
 * @author Tyham
 */
public class GameView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameView.class.getName());
    private javax.swing.JPanel currentPanel;
    private GameScreen gameScreen;
    private FileChooser fileChooser;
    private CreatePlayers createPlayers;
    private SummaryScreen summaryScreen;
    private SelectedQuestion selectedQuestion;
    
    /**
     * Creates new form JeopardyWindow
     * @param control
     */
    public GameView(GameScreen gameScreen, FileChooser fileChooser, CreatePlayers createPlayers, SelectedQuestion selectedQuestion, SummaryScreen summaryScreen) 
    {
        initComponents();
        
        this.gameScreen = gameScreen;
        this.gameScreen.setMainFrame(this);

        this.fileChooser = fileChooser;
        this.fileChooser.setMainFrame(this);

        this.createPlayers = createPlayers;
        this.createPlayers.setMainFrame(this);

        this.selectedQuestion = selectedQuestion;
        this.selectedQuestion.setMainFrame(this);

        this.summaryScreen = summaryScreen;
        this.summaryScreen.setMainFrame(this);
        
        // Set up the layout before adding components
        getContentPane().setLayout(new java.awt.BorderLayout());
        
        currentPanel = this.fileChooser;
        add(currentPanel, java.awt.BorderLayout.CENTER);
        
        // Pack and center the window
        pack();
        setLocationRelativeTo(null); // Center the window
        setVisible(true);
    }

    public void switchPanel(javax.swing.JPanel newPanel)
    {
        remove(currentPanel);
                
        currentPanel = newPanel;
        add(currentPanel, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
        pack();
    }
    public CreatePlayers getCreatePlayers() { return this.createPlayers; }
    public SummaryScreen getSummaryScreen() { return this.summaryScreen; }
    public GameScreen getGameScreen() { return this.gameScreen; }
    public SelectedQuestion getSelectedQuestion() { return this.selectedQuestion;}

    public void setCreatePlayers(CreatePlayers cp) { this.createPlayers = cp; }
    public void setSummaryScreen(SummaryScreen ss) { this.summaryScreen = ss; }
    public void setGameScreen(GameScreen gs) { this.gameScreen = gs; }
    public void setSelectedQuestion(SelectedQuestion sq) { this.selectedQuestion = sq; }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
