// /*
//  * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
//  * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
//  */
// package yainted.gui.deprecated;

// import yainted.gui.CreatePlayers;
// import yainted.gui.GameView;

// /**
//  *
//  * @author Tyham
//  */
// public class SetupScreen extends javax.swing.JPanel {

    
    
//     /**
//      * Creates new form SetupScreen
//      * @param frame
//      */
//     private GameView mainFrame;
    
//     public SetupScreen(GameView frame) {
//         initComponents();
//         this.mainFrame = frame;
//     }

//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//     private void initComponents() {

//         buttonGroup1 = new javax.swing.ButtonGroup();
//         jLabel1 = new javax.swing.JLabel();
//         jComboBox1 = new javax.swing.JComboBox<>();
//         jButton1 = new javax.swing.JButton();

//         jLabel1.setText("Please Select a File Format");

//         jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XML", "JSON", "CSV" }));

//         jButton1.setText("Accept");
//         jButton1.addActionListener(this::jButton1ActionPerformed);

//         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//         this.setLayout(layout);
//         layout.setHorizontalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addContainerGap(140, Short.MAX_VALUE)
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                         .addComponent(jLabel1)
//                         .addGap(119, 119, 119))
//                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                             .addComponent(jButton1)
//                             .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addGap(162, 162, 162))))
//         );
//         layout.setVerticalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addGap(48, 48, 48)
//                 .addComponent(jLabel1)
//                 .addGap(57, 57, 57)
//                 .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
//                 .addComponent(jButton1)
//                 .addGap(45, 45, 45))
//         );
//     }// </editor-fold>//GEN-END:initComponents

//     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//         // TODO add your handling code here:
//         String selectedFormat = jComboBox1.getSelectedItem().toString();
//         this.mainFrame.sendFileFormat(selectedFormat);
//         this.mainFrame.switchPanel(new CreatePlayers(mainFrame));
//     }//GEN-LAST:event_jButton1ActionPerformed


//     // Variables declaration - do not modify//GEN-BEGIN:variables
//     private javax.swing.ButtonGroup buttonGroup1;
//     private javax.swing.JButton jButton1;
//     private javax.swing.JComboBox<String> jComboBox1;
//     private javax.swing.JLabel jLabel1;
//     // End of variables declaration//GEN-END:variables
// }
